### ISSUE TITLE
I2C Slave Mode Support

### ISSUE THREAD

**Issue by mbt28** [tenbaht/sduino#105] opened 2020-08-07 13:22 UTC
Hi,

I checked the wiki but I couldnt see anything referring to I2C slave. Is it possible to use I2C slave with Sduino?

Thanks

**Comment by tenbaht** [comment] 2020-10-13 21:35
No, not yet. Would be great, but am a little short on time.
duplicate of #79

**Closed as completed by tenbaht** 2020-10-13 21:35 UTC
Labels: feature request
